### ISSUE TITLE
get_long_description() in setup.py fetchs too-many dependencies on build

### ISSUE THREAD

**Issue by ankostis** [vinci1it2000/syncing#3]
`setup.py` scripts are supposed to import as little as possible because they python-environment might not have all those libraries installed.
And by invoking *sphinx-builder*, it loads in *build-time* all libraries used by docs (matplotlib & graphviz).

- Practically it is not easy to test the project because of all those dependencies  
- Conda build needs special handlng.

## Alternative
use [the pure-python code from pandalone](https://github.com/pandalone/pandalone/blob/master/setup.py#L65-L112) to clean README.rst for PyPi.

**Comment by vinci1it2000** [comment]
The long description is used in dev mode to build the package for pypi. With Sphinx I am sure of the result, so I don’t maintain a custom script to render the description of pypi. I can add an environment variable to disable it. Is it okay for you?

**Comment by ankostis** [comment]
It does not belng in the setup.py - no complex code in these beasts :-)
